# Generated by Django 3.2.4 on 2021-11-01 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0002_completedticketdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketdata',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
