# Generated by Django 3.2.4 on 2021-11-01 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0003_alter_ticketdata_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketdata',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
